### ISSUE TITLE
Error displayed in PowerApp

### ISSUE THREAD

**Issue by aqyx** [OfficeDev/microsoft-teams-apps-visitormanagement#3]
The following error is displayed when opening the PowerApp.

VisitorManagementUserGallery.Run failed: { "error": { "code": 502, "source": "uk-001.azure-apim.net", "clientRequestId": "e64626ec-9304-404e-a754-d6770423f788", "message": "BadGateway", "innerError": { "error": { "code": "NoResponse", "message": "The server did not received a response from an upstream server. Request tracking id '08586054101973395960802446607CU15'." } } } }

When checking the Flow run:
Unable to process template language expressions for action 'Add_to_time' at line '1' and column '2316': 'In function 'addtotime', the value provided for date time string '31/07/2020' was not valid. The datetime string must match ISO 8601 format.'.

The Visitor List SharePoint list is being updated, but any visitors (confirmed or otherwise) are not visible within the admin applicaiton.

**Comment by cristianoag** [comment]
Same error over here. App is not working ok.

**Comment by shivamkumari713** [comment]
The following error is displayed when opening the PowerApp.

VisitorManagementUserGallery.Run failed: { "error": { "code": 502, "source": "india-001.azure-apim.net", "clientRequestId": "622953a1-fb45-4839-9267-5ee2989d811f", "message": "BadGateway", "innerError": { "error": { "code": "NoResponse", "message": "The server did not received a response from an upstream server. Request tracking id '0858604385204718045000562783CU13'." } } } }

when checking flow 
Action 'Parse_JSON' failed under (ParseJSON)
"message": "Invalid type. Expected String but got Null.",

**Comment by aqyx** [comment]
Exact same issue today with the date parsing when deploying for a client today. Disappointing that I raised this three months ago and the owners haven't fixed or given a solution to the issue. SharePoint list is updating correctly when new requests are added, but the two gallery flows (user and security) fail multiple times whenever someone opens the app.

VisitorManagementSecurityTeamGallery.Run failed: { "error": { "code": 502, "source": "uk-001.azure-apim.net", "clientRequestId": "5589e8c6-64d2-46c6-99d0-ce0e749625c7", "message": "BadGateway", "innerError": { "error": { "code": "NoResponse", "message": "The server did not received a response from an upstream server. Request tracking id '08585978002845405671468960019CU27'." } } } }

![image](https://user-images.githubusercontent.com/13008664/97310738-7a6d3500-185b-11eb-9219-6dabc438c31b.png)

@cristianoag Thanks for replying, but that's not the cause of the issue. All SharePoint activities within the various flows were checked both in my original case and today's.

**Comment by shayne-x** [comment]
I noticed this issue as well. It seems it has something to do with the regional settings on your device or browser. I'm yet to figure it out but i simply switched computers to "bypass" the error.

**Comment by aqyx** [comment]
Simplest fix is to change the two gallery flows, so rather than pulling the date from the app (in the incorrect format due to regional differences) we can get it from an expression. This allows the two flows to run correctly, and both apps work perfectly fine following the change.

![image](https://user-images.githubusercontent.com/13008664/97690029-55afd200-1a94-11eb-9680-e0524b6f3858.png)
