### ISSUE TITLE
Error when importing package

### ISSUE THREAD

**Issue by GResplandy** [OfficeDev/microsoft-teams-apps-visitormanagement#5]
Good afternoon,
I am following the deployment instructions for the Visitor Management App and getting this error when importing the first package in Power Automate (CreateSharePointListsVisitorManagement zip package):
The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics CRM are not supported.
Indeed in the package there are no such files, only the json ones.
Thanks in advance for your help on this.
Best

**Comment by v-smahaj** [comment]
After logging into Power Automate portal, navigate to My Flows  then Click on Import at the top rail of the page and select CreateSharePointListsVisitorManagement zip package.
Let us know if issue still persists.
