### ISSUE TITLE
Error con la app de visitor management

### ISSUE THREAD

**Issue by maye-vargas** [OfficeDev/microsoft-teams-apps-visitormanagement#8]
![image](https://user-images.githubusercontent.com/86726190/141007351-caa6e872-4a52-4d43-a758-8638135654fe.png)

**Comment by vivekchandra-conexiq** [comment]
Hi, I get the same error message. Were you able to find a solution ?

**Comment by maye-vargas** [comment]
Hola, si, encontré una solución, el problema esta en una formula en power app, en cuanto a un dato que trae la fecha, no debe traer fecha y hora, si no, solo la fecha

**Comment by salmah52** [comment]
same error message. Any solution for it yet?

**Comment by PowerThomas** [comment]
Remove the flow in the datasource:
![image](https://user-images.githubusercontent.com/38666925/154140430-9daa1a6c-34fa-4d1e-a1a2-f49788b7f96d.png)

Next add the flow again:
![image](https://user-images.githubusercontent.com/38666925/154140615-75d0aaca-bd6c-41df-959f-33b40ba44865.png)

Then the error should gone. Make sure to not touch any formulas.
